# Generated by Django 4.2.2 on 2023-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('domain', models.CharField(max_length=300)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=300)),
                ('locality', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
            ],
        ),
    ]
